### ISSUE TITLE
reverse_argument_order not working or my fault?

### ISSUE THREAD

**Issue by sebseb7** [michaelkamprath/bespokeasm#15]
isa.yaml
```
      register_a:
        type: register
        register: a
        bytecode:
          value: 1
          size: 4
          position: suffix
      register_b:
        type: register
        register: b
        bytecode:
          value: 2
          size: 4
          position: suffix
      register_c:
        type: register
        register: c
        bytecode:
          value: 3
          size: 4
          position: suffix


...


        byte_code:
          value: 128
          size: 8
        operands:
          count: 3
          operand_sets:
            reverse_argument_order: true
            list:
              - register
              - register
              - register
```

pretty-print from assember:
```
      36 |     ld a,b,c              |  0x8016 | 0x80 | 10000000 |
         |                           |  0x8017 | 0x12 | 00010010 |
         |                           |  0x8018 | 0x30 | 00110000 |
```
it generates 0x80 0x12 0x30, when I expected 0x80 0x32 0x10

**Comment by sebseb7** [comment]
or maybe have an "order" attribute for operand_sets
```
   order: [3,2,1]
´´´

**Comment by michaelkamprath** [comment]
That could be a syntax.

Also, just curious, how is this a need for you? The reason for potentially reversing the argument values is that the microcode that the byte code maps to might be more efficient in dealing with the later argument first. My guess is that you are parsing the byte code like an immediate argument (which is fair, just something I didn't anticipate). In that case, you might consider using `enumeration` operand type instead, because they can be configured to emit an argument, which can be reversed. 

For example, for this configuration:
```yaml
...
operand_sets:
  enums:
    operand_values:
      register_enum:
        type: enumeration
        argument:
          size: 4
          byte_align: false
          value_dict:
            aa: 1
            bb: 2
            cc: 3
...
  ed:
    byte_code:
      value: 136
      size: 8
    operands:
      count: 3
      operand_sets:
        reverse_argument_order: true
        list:
          - enums
          - enums
          - enums
...
```
then for the instruction `ed aa,bb,cc`, the bytes `[0x88, 0x32, 0x10]` will be emitted. Note that if you define `a`, `b,`, and `c` as a register, it cannot be used as an enumeration key.
