### ISSUE TITLE
reverse_bytecode_order problem

### ISSUE THREAD

**Issue by sebseb7** [michaelkamprath/bespokeasm#16]
it works for opcode 0x24 but not for opcode 0x25 (partially)

register dd is 0xa0, for opcode 0x24 it is placed last, for 0x25 placed first.

https://github.com/sebseb7/logicpu/blob/master/isa.yaml

```
      34 |     ld dd,0x81,[var4]                  |  0x8030 | 0x25 | 00100101 | 
         |                                        |  0x8031 | 0xa0 | 10100000 |
         |                                        |  0x8032 | 0x00 | 00000000 |
         |                                        |  0x8033 | 0x02 | 00000010 |
         |                                        |  0x8034 | 0x81 | 10000001 |
      35 |     ld dd,b,c                          |  0x8035 | 0x24 | 00100100 | 
         |                                        |  0x8036 | 0x32 | 00110010 |
         |                                        |  0x8037 | 0xa0 | 10100000
```
```
      - var4b:
        byte_code:
          value: 36
          size: 8
        operands:
          count: 3
          operand_sets:
            reverse_bytecode_order: true
            list:
              - wo_register
              - register
              - register
      - var6:
        byte_code:
          value: 37
          size: 8
        operands:
          count: 3
          operand_sets:
            reverse_bytecode_order: true
            list:
              - register_except_a
              - integer
              - address
```
